### ISSUE TITLE
Mocker crashes, injected alias doesn't seem to exist

### ISSUE THREAD

**Issue by bawolf** [skylerparr/syringe#6] opened 2019-09-30 19:13 UTC
Sample project here: https://github.com/bawolf/firebasex/
This app is a small state machine that grabs public keys from a google endpoint that are released ~once a day and compares them to tokens coming from clients.

* `Firebasex` is the parent with all the business logic which injects the `KeyRegistry`
* `KeyRegistry` is an agent that stores a map of `id => public key`
* `GoogleKeys` is a wrapper around the actual web request to fetch the map of public keys

It's convenient to mock the registry when testing `Firebasex` because that lets me assume a few specific conditions (namely a public key is found for that id, or it's not) without having to mock out the whole map.

When testing the registry it would be convenient to mock `GoogleKeys` like in the test shown. When I run the test I get this error:

```bash
** (Mix) Could not start application firebasex: Firebasex.Application.start(:normal, []) returned an error: shutdown: failed to start child: Firebasex.KeyRegistry
    ** (EXIT) exited in: GenServer.call(Mocker, {Injector.Firebasex.GoogleKeys, :fetch, [], #PID<0.184.0>}, 5000)
        ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started

12:11:02.765 [info]  Application firebasex exited: Firebasex.Application.start(:normal, []) returned an error: shutdown: failed to start child: Firebasex.KeyRegistry
    ** (EXIT) exited in: GenServer.call(Mocker, {Injector.Firebasex.GoogleKeys, :fetch, [], #PID<0.184.0>}, 5000)
        ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```

Any ideas? Am I missing something obvious?

**Comment by skylerparr** [comment] 2019-09-30 19:27
Strangely, `mix deps.get` is just hanging for me ATM, so I'm not able to directly verify. But, I think I see the issue. You're mocking this module `mock(Firebasex.GoogleKeys)` and you're intercepting a different module atom: `mock_reg = intercept(GoogleKeys, :fetch, [], with: fn -> %{"a" => "hello"} end)` which is effectively a different module. Try aliasing with `alias Firebasex.GoogleKeys`, and updating your mock call `mock(GoogleKeys)` and see if you get a different result.

**Comment by bawolf** [comment] 2019-09-30 20:49
I pushed an update. I'm still getting the same error on my local though.

**Comment by skylerparr** [comment] 2019-09-30 21:29
I was finally able to `mix deps.get` and I've debugged the issue. The issue is not with your tests actually, it's the fact that the application is trying to start the `Firebasex.KeyRegistry` before the mocker has been started (https://github.com/bawolf/firebasex/blob/master/lib/firebasex/application.ex#L12). In my experience, I find testing GenServers (in your case an Agent) that are started by the Application difficult to test since they start before ExUnit starts. I recommend not starting applications when `MIX_ENV=test` because you'll run into other issues when trying to test GenServers (especially WRT named GenServers or testing what should happen during `start_link`, unless there are Applications outside of your project that need to be started.). If that isn't an option, you can update your `mix.exs` to start the mocker (`Mocker.start_link()`) as part of the application definition and only do it for `Mix.env == :test`. 

Does that make sense? Let me know if you need further clarification.

**Comment by bawolf** [comment] 2019-09-30 22:52
Yeah, totally reasonable! I when with the start mocker in application.ex file in the test environment because that involved updating the fewest things, although is does muddy up feature code a bit. I might revisit in the future. I'm happy to close this or provide any details that might help write a gotcha here.

**Comment by skylerparr** [comment] 2019-09-30 22:54
Go ahead and close it. I'll update the readme tonight with this gotcha. It
helps to have this issue in the wild as documentation too.

**Closed as completed** 2019-10-01 17:51 UTC
